version: '3.10'

services:
  web:
    build: .
    command: python /projects/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/projects
    ports:
      - 8000:8000

    db:
      image: postgress:14
      environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"